anothertime:
  broker-url: tcp://antonus.org:7001
  awtrix-url: http://192.168.1.92
  awtrix-topic: awtrix_986dd0
  pause-if-hidden: true
  week:
    start-sunday: false
    style: dotted2
    day-color: '#ff00ff'
    week-color: '#00bbff'
  time:
    separator: fade
    animation: fade
  seconds:
    color: '#ff00ff'
  widgets:
    animation: scroll
    temperature:
      fahrenheit: false
spring:
  threads:
    virtual:
      enabled: true